### ISSUE TITLE
Selection of only few resamples for analysis

### ISSUE THREAD

**Issue by Degradome** [genular/simon-frontend#53]
**Describe the bug**
After running the multi-set intersection, the user should be able to select only a few resamples for the final analysis. This is specifically important when a too large number of resamples have been generated. Even though, there is an option for users to select only some resamples, the analysis starts on all and not only on selected resamples

**To Reproduce**
1. Go to 'Analysis’
2. Click on 'Multi-set intersection'
3. Click on ‘Validate data’
4. Uncheck all resamples
5. Check only first two resamples
6. Click on ‘Process’
7. Go back to the ‘Dashboard’
8. See error: Resamples – number of all resamples and not only two as we selected
9. Analysis continues with all resamples 

**Expected behavior**
The analysis should start with only selected resamples.

**Desktop (please complete the following information):**
- OS: Win10pro
- Browser: Firefox
- Version: 72.0.2 (64-bit)

**Comment by LogIN-** [comment]
Done in https://github.com/genular/simon-frontend/commit/bd56ef8e5579efa4535a3dd3567b6c92bc184f29
