### ISSUE TITLE
Describe a progress of the analysis

### ISSUE THREAD

**Issue by Degradome** [genular/simon-frontend#54]
**Describe the bug**
The analysis processing should be better described to reflect the progress under 'Status' in the Dashboard. Now it only says 'Processing'. 

The status instead of 'Processing' should be the percentage of the finished analysis or remaining time for the analysis.

**Comment by LogIN-** [comment]
Close in https://github.com/genular/simon-frontend/commit/e46f0c163e6363f2dcc46034f2d3635404e0ac9f
