### ISSUE TITLE
Issue about SIMON Web application use

### ISSUE THREAD

**Issue by Zhenshuang** [genular/simon-frontend#69]
The SIMON is a amazing work and it extremely useful for some researchers who don't  know how to carry out Machine Learning on their project. I am a PhD student from Huazhong Agricultural University in China and my research is mainly about genomic prediction. Recently, I want to perform some ML analysis through SIMON web application, but the "CHECK OUT DEMO" tab were clicked, "Unfortunately server is currently temporarily unavailable" will pop up, and it is same situation when try again later. How to fix it? Thanks.

**Comment by LogIN-** [comment]
Demo server is not intended to perform any analysis on it. In fact all functions regarding to ML functionality are there disabled.
Demo is used just  to demonstrate SIMON gui. I suggest you install docker container on your own PC if you wish to use it.
