### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by jIskCoder** [genular/simon-frontend#71]
**Describe the bug**
When running
sudo docker pull genular/simon

I got 

failed to register layer: Error processing tar file(exit status 1): write /var/lib/mysql/ib_logfile0: no space left on device

I am running on a VM.

Any one faced this issue? How can I solve it?

**Comment by LogIN-** [comment]
Hi @jIskCoder thanks for reporting a bug. It is really hard to say without more info.
Are you sure you have enough space on your device, on your virtual VM disk or on physical host machine drive?

**Comment by jIskCoder** [comment]
There is enough space.
![VM-filesystem](https://user-images.githubusercontent.com/34782134/99738563-e1aa9c00-2b1e-11eb-8be4-f17c987fb530.png)

**Comment by LogIN-** [comment]
HI @jIskCoder,
Thanks for shots, I really think this is not SIMON related bug. Not sure if this is VM screenshots or the host machine but it looks like you have only 10GB mounted on / ... I suggest increasing that size. 

Also I am mot exactly sure how much of size SIMON docker image needs but I would leave minimum of 10GB only for it if not more. So my suggestion is to prune whole docker system and volumes, increase VM file-system and pull the image.
