### ISSUE TITLE
Bug report from the localhost on firefox, Mac Catalina

### ISSUE THREAD

**Issue by polakme** [genular/simon-frontend#82]
Message:String contains an invalid character
Info: vue-component-32-ElButton error in v-on handler
Url: http://localhost:3010/#/apps/simon/start-exploration

Trace back 
                                downloadPlotImage@http://localhost:3010/6.7b3b2f1ef780ecc90bd4.js:1:30344
click@http://localhost:3010/6.7b3b2f1ef780ecc90bd4.js:1:177294
Ve@http://localhost:3010/vendor.bundle.8c9396458d6876b3e093.js:2:1087376
n@http://localhost:3010/vendor.bundle.8c9396458d6876b3e093.js:2:1089164
Ve@http://localhost:3010/vendor.bundle.8c9396458d6876b3e093.js:2:1087376
./node_modules/vue/dist/vue.runtime.esm.js/</</e.prototype.$emit@http://localhost:3010/vendor.bundle.8c9396458d6876b3e093.js:2:1110366
handleClick@http://localhost:3010/vendor.bundle.8c9396458d6876b3e093.js:2:437565
Ve@http://localhost:3010/vendor.bundle.8c9396458d6876b3e093.js:2:1087376
n@http://localhost:3010/vendor.bundle.8c9396458d6876b3e093.js:2:1089164
gi/o._wrapper@http://localhost:3010/vendor.bundle.8c9396458d6876b3e093.js:2:1120566

**Comment by LogIN-** [comment]
Hi @polakme ,
Thank you for your bug report.

It would be great if you could provide us with description, SIMON version and screenshot on what where you doing when bug occurred. 

Also please be sure to use latest SIMON version and let me know is bug is also occurring there.
You can reinstall SIMON by using following commands (all data will be lost):
1. Delete existing SIMON instance
```
## 1. Stop currently running docker container
docker stop genular
## 2. Delete docker SIMON data storage
docker volume rm genular_data
## 3. Prune docker system and remove all containers, images, volumes with one command.
docker system prune -a
```
2. Install latest SIMON build
```
docker run --rm --detach --name genular --tty --interactive --env IS_DOCKER='true' --env TZ=Europe/London --volume genular_data:/mnt/usrdata --publish 3010:3010 --publish 3011:3011 --publish 3012:3012 --publish 3013:3013 genular/simon:latest
```

**Comment by polakme** [comment]
Thank you
I downloaded SIMON literally yesterday, using the link you provided in the paper, so I presume it is the latest
There are 4 bugs occurring on the bug symbol,
Version information:
genular 0.1.0 (production)
Developed by the genular community.

I will re-install following the code in your e-mail, but it is running analysis for me at the mo! So when it’s done
Thanks
Marta

Dr Marta E Polak
Associate Professor, Sir Henry Dale Wellcome Trust Fellow

Clinical and Experimental Sciences, Faculty of Medicine, University of Southampton,
Mailpoint 813, Level E, South Block, Southampton General Hospital, Southampton, SO16 6YD, UK
tel (+44) 02381205727
https://www.southampton.ac.uk/medicine/about/staff/mep1p07.page

On 3 Feb 2021, at 13:00, LogIN- <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This e-mail originated outside the University of Southampton.


Hi @polakme<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpolakme&data=04%7C01%7Cm.e.polak%40soton.ac.uk%7C595e46b90e85418269e308d8c843bdd8%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637479540563016243%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FTBFwsGUilbtGPbGYLS%2Bor8HxRBMGsTUEOElk8A1xUs%3D&reserved=0> ,
Thank you for your bug report.

It would be great if you could provide us with description, SIMON version and screenshot on what where you doing when bug occurred.

Also please be sure to use latest SIMON version and let me know is bug is also occurring there.
You can reinstall SIMON by using following commands (all data will be lost):

  1.  Delete existing SIMON instance

## 1. Stop currently running docker container
docker stop genular
## 2. Delete docker SIMON data storage
docker volume rm genular_data
## 3. Prune docker system and remove all containers, images, volumes with one command.
docker system prune -a


  1.  Install latest SIMON build

docker run --rm --detach --name genular --tty --interactive --env IS_DOCKER='true' --env TZ=Europe/London --volume genular_data:/mnt/usrdata --publish 3010:3010 --publish 3011:3011 --publish 3012:3012 --publish 3013:3013 genular/simon:latest

**Comment by LogIN-** [comment]
HI @polakme,

We had multiple feature and bug improvements since the published version (0.1.0).
I warmly suggest trying to reinstall SIMON using code from my 1st comment since than you should have the latest code.

Thanks!

**Comment by polakme** [comment]
Fab!
Will do, thanks
BTW, the tool is absolutely awesome, thanks a million for developing it. Will get my life million times easier in getting biology students inspired for ML
BW
Marta



Dr Marta E Polak
Associate Professor, Sir Henry Dale Wellcome Trust Fellow

Clinical and Experimental Sciences, Faculty of Medicine, University of Southampton,
Mailpoint 813, Level E, South Block, Southampton General Hospital, Southampton, SO16 6YD, UK
tel (+44) 02381205727
https://www.southampton.ac.uk/medicine/about/staff/mep1p07.page

On 3 Feb 2021, at 13:43, LogIN- <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This e-mail originated outside the University of Southampton.


HI @polakme<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpolakme&data=04%7C01%7Cm.e.polak%40soton.ac.uk%7C45f563d66e5046a6147308d8c849a2be%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637479565918793116%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2%2BNwHOwcGW%2B9SHuTANeEI8KzoS7Fu4dGQBCrs3Dexc4%3D&reserved=0>,

We had multiple feature and bug improvements since the published version (0.1.0).
I warmly suggest trying to reinstall SIMON using code from my 1st comment since than you should have the latest code.

Thanks!

**Comment by LogIN-** [comment]
Hi @polakme,

Great. I really do hope so. Feel free (you or your students) to send over any bugs or suggestions for feature releases via our github, like for this one.
 
We are currently in process in adding some neat features for next release so stay tuned.. :)

**Comment by polakme** [comment]
Hi,
So I have followed the instructions, and the version info on the settings screen stays the same:

Version information:
genular 0.1.0 (production)
Developed by the genular community

Do you want me to check the versions somewhere else?
BW
Marta


Dr Marta E Polak
Associate Professor, Sir Henry Dale Wellcome Trust Fellow

Clinical and Experimental Sciences, Faculty of Medicine, University of Southampton,
Mailpoint 813, Level E, South Block, Southampton General Hospital, Southampton, SO16 6YD, UK
tel (+44) 02381205727
https://www.southampton.ac.uk/medicine/about/staff/mep1p07.page

On 3 Feb 2021, at 13:50, LogIN- <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This e-mail originated outside the University of Southampton.


Hi @polakme<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpolakme&data=04%7C01%7Cm.e.polak%40soton.ac.uk%7C5ed786660fa3446df47008d8c84ab724%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637479570522105970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WpxNSm0OsQKgjQWs8%2FWenit5FMVhcBpjFjcW32vLcb0%3D&reserved=0>,

Great. I really do hope so. Feel free (you or your students) to send over any bugs or suggestions for feature releases via our github, like for this one.

We are currently in process in adding some neat features for next release so stay tuned.. :)

**Comment by LogIN-** [comment]
Hi @polakme,

If you followed my instructions from above you should have the latest production version, you can ignore it says 0.1.0 since this will be updated with official release.
---
I suggest to try to do some analysis and let me know if you still have the bug. 
If you do have a bug, I would really appreciate if you could help me to fix it by providing description, screenshot etc.. so I can understand better whats going on.

Thanks!

**Comment by polakme** [comment]
Thanks,
Looks like my major problem has been fixed, but I am not able to validate data now (using same dataset as before), message is There was an error processing your request. Please try again latter - is that because the server is busy?

M


Dr Marta E Polak
Associate Professor, Sir Henry Dale Wellcome Trust Fellow

Clinical and Experimental Sciences, Faculty of Medicine, University of Southampton,
Mailpoint 813, Level E, South Block, Southampton General Hospital, Southampton, SO16 6YD, UK
tel (+44) 02381205727
https://www.southampton.ac.uk/medicine/about/staff/mep1p07.page

On 4 Feb 2021, at 14:09, LogIN- <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This e-mail originated outside the University of Southampton.


Hi @polakme<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpolakme&data=04%7C01%7Cm.e.polak%40soton.ac.uk%7C2e423351ecca4cc9cf2008d8c9167d0f%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637480445775675986%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4TZY4Bu0pwtSiASAMBti0yPzK8vnas17OUFgY88LsLo%3D&reserved=0>,

If you followed my instructions from above you should have the latest production version, you can ignore it says 0.1.0 since this will be updated with official release.

________________________________

I suggest to try to do some analysis and let me know if you still have the bug.
If you do have a bug, I would really appreciate if you could help me to fix it by providing description, screenshot etc.. so I can understand better whats going on.

Thanks!

**Comment by LogIN-** [comment]
Hi @polakme,

hmm, no SIMON is hosted on your own PC so this should not be an issue.
This is very strange and it should not happen. I just tried in my PC on my data and it works without an issue.

Can you please try to stop docker container and start it again:
```
## To stop currently running container
docker stop genular

## To start it again
docker run --rm --detach --name genular --tty --interactive --env IS_DOCKER='true' --env TZ=Europe/London --volume genular_data:/mnt/usrdata --publish 3010:3010 --publish 3011:3011 --publish 3012:3012 --publish 3013:3013 genular/simon:latest
```

If the problem persist, it would be great if we could reproduce it so I can fix it.
In order to help you maybe you could share the data in question with me and tell me all the exact options you selected?

**Comment by polakme** [comment]
I have tried with your data too - cyclist, got me an error as per attached screenshot
Will re-instal again

M
[cid:6c6661d2-ffd5-4e1e-bee4-ee1c7f2be735@GBRP265.PROD.OUTLOOK.COM]

It was running OK yesterday…

Apologies, cannot share my original data, as it is from patients….
BW
Marta


On 4 Feb 2021, at 14:45, LogIN- <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This e-mail originated outside the University of Southampton.


Hi @polakme<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpolakme&data=04%7C01%7Cm.e.polak%40soton.ac.uk%7C1e76640f349b47c1d5df08d8c91b7953%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637480467136604188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wE%2BSMIuJwVQ0BFVEHQ6KA7LDaWiaI05JBqQMj%2BfZZSk%3D&reserved=0>,

hmm, no SIMON is hosted on your own PC so this should not be an issue.
This is very strange and it should not happen. I just tried in my PC on my data and it works without an issue.

Can you please try to stop docker container and start it again:

## To stop currently running container
docker stop genular

## To start it again
docker run --rm --detach --name genular --tty --interactive --env IS_DOCKER='true' --env TZ=Europe/London --volume genular_data:/mnt/usrdata --publish 3010:3010 --publish 3011:3011 --publish 3012:3012 --publish 3013:3013 genular/simon:latest


If the problem persist, it would be great if we could reproduce it so I can fix it.
In order to help you maybe you could share the data in question with me and tell me all the exact options you selected?

**Comment by LogIN-** [comment]
Hi @polakme,

That is completely fine Please note if you just stop and start it than its the two commands I mentioned previously, but if you wish to do full reinstall than are all the commands needed as I wrote yesterday..

I will open a new feature request to implement method of system log display, so we will have better picture on why such bugs occur.

**Comment by polakme** [comment]
Hi,
I have stopped and restarted, nothing changed (i.e. still getting the error I sent earlier with cyclists - it used to work before with the not-up-to date version)
I have re-installed and re-installed, and now I cannot log in (I had this error before, after first re-install it did not recognise my login/password. When I try to send “reset password” nothing happens => button does not work).

I am a bit puzzled, these errors seem fairly random…

Hope you can help, happy to connect at some point to demonstrate if you cannot reproduce.

My environment:
Mac OS Catalina 10.15.7
Firefox 85.0

Thanks!



On 4 Feb 2021, at 14:54, LogIN- <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This e-mail originated outside the University of Southampton.


Hi @polakme<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpolakme&data=04%7C01%7Cm.e.polak%40soton.ac.uk%7Ca19255779e0443b42e4408d8c91cc527%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637480472812596079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6kuh0PSBLAd3yD8cwcR2LGaXg2SjpSCmhuoJJ%2BwfPaA%3D&reserved=0>,

That is completely fine Please note if you just stop and start it than its the two commands I mentioned previously, but if you wish to do full reinstall than are all the commands needed as I wrote yesterday..

I will open a new feature request to implement method of system log display, so we will have better picture on why such bugs occur.

**Comment by LogIN-** [comment]
Hi @polakme,

It is normal that after reinstall username and password are not recognized and you need to create an account again, since database is deleted when you do that.

I tried fresh install on my PC and tried with multiple different data-sets, unfortunately it was always working in my case.
I would says its something really specific but cannot say for sure what exactly.
I have few ideas what it could be, but as I say cannot say for sure in this stage.

It would be great to connect (zoom/teams etc..) so you can demonstrate me the issue.
If this is okay with you, please before our meeting delete everything again so we will be sure we are on clear track.

Execute following commands from your terminal and dont do anything else until we connect together:
```
docker stop genular

docker volume rm genular_data

docker system prune -a --volumes

docker run --rm --detach --name genular --tty --interactive --env IS_DOCKER='true' --env TZ=Europe/London --volume genular_data:/mnt/usrdata --publish 3010:3010 --publish 3011:3011 --publish 3012:3012 --publish 3013:3013 genular/simon:latest
```

I really hope we can get to bottom of this and solve this issue.

I will send you my direct contact details by email.

Thanks!

**Comment by polakme** [comment]
Thanks!
I have now re-run all, and I can see the errors which are “stable” and not corrected by re-installation.

1) I am unable to download graphs from training summary - this generates errors. Easy to overcome with saving as, but error nonetheless. Bug reports are generated every time I try downloading the graph, I can send these over to you if useful

I can download the graphs from variable importance w/o problems

2) Model summary is not running - usually just returns info: try again later - this might be due to RAM/CPU? I am on 16GB RAM, 3.1 GHz Dual-Core Intel Core i7,

3) So far, every stop/start from the terminal results in errors, I need to re-instal every time to re-start SIMON

I appreciate these might be due to my Mac, no general, I will try to run on a different machine to see if these errors are resolved or not

Thanks a lot for your help
BW
Marta


On 5 Feb 2021, at 09:56, LogIN- <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This e-mail originated outside the University of Southampton.


Hi @polakme<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpolakme&data=04%7C01%7Cm.e.polak%40soton.ac.uk%7C2cde7a34ac034d83196508d8c9bc456b%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637481157741435202%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=90LcIu1OnNfBGfoXuAs%2BvDFuF09IJkm8dIiEluRuvpA%3D&reserved=0>,

It is normal that after reinstall username and password are not recognized and you need to create an account again, since database is deleted when you do that.

I tried fresh install on my PC and tried with multiple different data-sets, unfortunately it was always working in my case.
I would says its something really specific but cannot say for sure what exactly.
I have few ideas what it could be, but as I say cannot say for sure in this stage.

It would be great to connect (zoom/teams etc..) so you can demonstrate me the issue.
If this is okay with you, please before our meeting delete everything again so we will be sure we are on clear track.

Execute following commands from your terminal and dont do anything else until we connect together:

docker stop genular

docker volume rm genular_data

docker system prune -a --volumes

docker run --rm --detach --name genular --tty --interactive --env IS_DOCKER='true' --env TZ=Europe/London --volume genular_data:/mnt/usrdata --publish 3010:3010 --publish 3011:3011 --publish 3012:3012 --publish 3013:3013 genular/simon:latest


I really hope we can get to bottom of this and solve this issue.

I will send you my direct contact details by email.

Thanks!

**Comment by LogIN-** [comment]
Hi @polakme,

In order to run a model summary please be sure to select at least two models to compare.

Model summary plots are still unsupported when looking (selecting) only one model, but we are working on this and should be ready in next release.

When you execute following command it [doesn't really mean](https://docs.docker.com/engine/reference/commandline/run/) you are reinstalling SIMON, since if docker image is already deployed on your machine it will just use that one, unless you executed all previous steps to be sure that you deleted old image and data storage.
```
docker run --rm --detach --name genular --tty --interactive --env IS_DOCKER='true' --env TZ=Europe/London --volume genular_data:/mnt/usrdata --publish 3010:3010 --publish 3011:3011 --publish 3012:3012 --publish 3013:3013 genular/simon:latest
```
